cmv_site_home:
    path:     /
    defaults: { _controller: CmvSiteBundle:Site:index }
cmv_site_tri:
    pattern: /films-et-documentaires.html
    defaults: { _controller: CmvSiteBundle:Site:tri }
cmv_site_projets:
    pattern: /clips-videos.html
    defaults: { _controller: CmvSiteBundle:Site:clips }
cmv_site_actu:
    pattern: /actualites.html
    defaults: { _controller: CmvSiteBundle:Site:actu }
cmv_site_contact:
    pattern: /contacter.html
    defaults: { _controller: CmvSiteBundle:Contact:contact }
cmv_site_lire:
    pattern: /lire/{code}.html
    defaults: { _controller: CmvSiteBundle:Site:lire, code:0}