<?php

namespace Cmv\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getFilmsDocs(){
        $qb=$this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('CmvSiteBundle:Article','a')
            ->leftJoin('a.categorie','categorie')
            ->addSelect('categorie')
            ->leftJoin('categorie.categorieParent','categorieParent')
            ->addSelect('categorieParent')
            ->orderBy('a.dateSave','DESC')
            ->where('categorie in (1,4,5)')


            ;
        return $qb->getQuery()->getResult();
    }
    public function getClipsVideos(){
        $qb=$this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('CmvSiteBundle:Article','a')
            ->leftJoin('a.categorie','categorie')
            ->addSelect('categorie')
            ->leftJoin('categorie.categorieParent','categorieParent')
            ->addSelect('categorieParent')
            ->orderBy('a.dateSave','DESC')
            ->where('categorie = 3')


        ;
        return $qb->getQuery()->getResult();
    }
    public function getActu(){
        $qb=$this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('CmvSiteBundle:Article','a')
            ->leftJoin('a.categorie','categorie')
            ->addSelect('categorie')
            ->leftJoin('categorie.categorieParent','categorieParent')
            ->addSelect('categorieParent')
            ->orderBy('a.dateSave','DESC')
            ->where('categorie = 6')


        ;
        return $qb->getQuery()->getResult();
    }
}
