<?php

namespace Cmv\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieParentRepository extends EntityRepository
{
}
